### ISSUE TITLE
ERR Error running script

### ISSUE THREAD

**Issue by tdean787** [pgonzaleznetwork/sfdc-happy-soup#190]
Received this error when searching for an Opportunity custom field.

ERR Error running script (call to f_8f55ae4a3be429c6d38c5d5db3e80edf89197b64): @user_script:41: @user_script: 41: -OOM command not allowed when used memory > 'maxmemory'.
ReplyError: ERR Error running script (call to f_8f55ae4a3be429c6d38c5d5db3e80edf89197b64): @user_script:41: @user_script: 41: -OOM command not allowed when used memory > 'maxmemory'. at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12) at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)

**Comment by pgonzaleznetwork** [comment]
Sorry about that. I've fixed this now, can you please try again?
